### ISSUE TITLE
Update from 2.5.1 to 3.0.0 broke my website

### ISSUE THREAD

**Issue by ajaxthemestudios** [10up/classifai#732]
### Describe your question

I updated the plugin from my current version 2.5.1 to 3.0.0 and it broke the website. I had to disable the plugin to recover my website and then return to the old version.
WP threw the following errors:

```
[01-Mar-2024 21:47:51 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Classifai\Features\Feature::merge_settings() must be of the type array, string given, called in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 399 and defined in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php:394
Stack trace:
#0 C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php(399): Classifai\Features\Feature->merge_settings('1', Array)
#1 C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php(319): Classifai\Features\Feature->merge_settings(Array, Array)
#2 C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php(942): Classifai\Features\Feature->get_settings()
#3 C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php(57): Classifai\Features\Feature->is_feature_enabled()
#4 C:\laragon\www\mysite in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 394
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Thanks for the report @ajaxthemestudios. That error message is helpful but would also be helpful to know what features you currently have set up in ClassifAI? This way I can narrow down which of the features is causing this error. Thanks!

Edit: also what settings you have for each of those features would be helpful. I've tried to reproduce this and have not run into the same error yet. It's a fairly simple code change needed to resolve this but would like to be able to actually reproduce to ensure there's nothing else we're missing.

**Comment by ajaxthemestudios** [comment]
Thank you for getting back to us.

1. We have the Microsoft Azure Image Processing API connected with the automatic Image tagging featured checked and enabled.
2. We also have the IBM Watson Language Processing API connected but did not check or enable the automatic content classification of posts.

I believe these two were the initial features available when we first installed the plugin three years ago. Despite all the newer features, they are the only features we have been using and all updates performed have never broken the plugin until now. Hope the information helps.

Please see attached screenshot of the settings for these two features
![language-processing](https://github.com/10up/classifai/assets/10270584/630bc012-2bf3-42ef-b963-f70e182ad1d4)
![image-processing](https://github.com/10up/classifai/assets/10270584/3dc04c1a-446c-4826-9a32-464c752353e5)

**Comment by dkotter** [comment]
@ajaxthemestudios Thanks for the additional details. Unfortunately I've not been able to replicate the error you're getting, even with matching those settings as close as I can get. I do have a PR up (#733) to attempt to fix this but haven't been able to verify that for sure since I haven't gotten that error.

If you happen to have some time and a local/test environment to test that PR on, that would be super helpful to let us know if it fixes your error.

**Comment by ajaxthemestudios** [comment]
@dkotter, I updated the site again. It broke the site like before. Then I replaced the Feature.php file with the updated one and the site was restored.
The only thing showing in my debug log file now that is related to classifai are PHP warnings and notices. If you are interested in time, here they are below:

```
[05-Mar-2024 19:43:30 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:43:30 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:43:49 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:43:49 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:17 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:17 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:24 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:24 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:32 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:32 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:32 UTC] PHP Warning:  array_search() expects parameter 2 to be array, string given in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 702
[05-Mar-2024 19:44:32 UTC] PHP Notice:  String offset cast occurred in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 711
[05-Mar-2024 19:44:32 UTC] PHP Warning:  array_search() expects parameter 2 to be array, string given in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 702
[05-Mar-2024 19:44:32 UTC] PHP Notice:  String offset cast occurred in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 711
[05-Mar-2024 19:44:32 UTC] PHP Warning:  array_search() expects parameter 2 to be array, string given in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 702
[05-Mar-2024 19:44:32 UTC] PHP Notice:  String offset cast occurred in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 711
[05-Mar-2024 19:44:39 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:39 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:51 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:51 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:44:51 UTC] PHP Warning:  array_search() expects parameter 2 to be array, string given in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 702
[05-Mar-2024 19:44:51 UTC] PHP Notice:  String offset cast occurred in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 711
[05-Mar-2024 19:44:51 UTC] PHP Warning:  array_search() expects parameter 2 to be array, string given in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 702
[05-Mar-2024 19:44:51 UTC] PHP Notice:  String offset cast occurred in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 711
[05-Mar-2024 19:44:51 UTC] PHP Warning:  array_search() expects parameter 2 to be array, string given in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 702
[05-Mar-2024 19:44:51 UTC] PHP Notice:  String offset cast occurred in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\Feature.php on line 711
[05-Mar-2024 19:45:04 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:45:04 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:45:07 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
[05-Mar-2024 19:45:07 UTC] PHP Warning:  Illegal string offset 'caption' in C:\laragon\www\mysite\wp-content\plugins\classifai-stable\includes\Classifai\Features\DescriptiveTextGenerator.php on line 316
```

Thanks and regards

**Comment by dkotter** [comment]
@ajaxthemestudios Thanks for the additional errors, those were also helpful. I've made additional changes to PR #733 and I think it addresses all the issues you've run into so far.
